rhodep: Add qcrilhook into boot jars * For some reason qti phone can't load class
03-02 09:39:02.292  2754  2754 D QtiPhoneApp: onCreate
03-02 09:39:02.293  2754  2754 D AndroidRuntime: Shutting down VM
03-02 09:39:02.293  2754  2754 E AndroidRuntime: FATAL EXCEPTION: main
03-02 09:39:02.293  2754  2754 E AndroidRuntime: Process: com.qti.phone, PID: 2754
03-02 09:39:02.293  2754  2754 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/qualcomm/qcrilhook/QcRilHookCallback;
03-02 09:39:02.293  2754  2754 E AndroidRuntime: at com.qti.phone.QtiPhoneApp.onCreate(QtiPhoneApp.java:18)
03-02 09:39:02.293  2754  2754 E AndroidRuntime: at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1322)
03-02 09:39:02.293  2754  2754 E AndroidRuntime: at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1488)
03-02 09:39:02.293  2754  2754 E AndroidRuntime: at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1404)
03-02 09:39:02.293  2754  2754 E AndroidRuntime: at android.app.ActivityThread.handleReceiver(ActivityThread.java:4453)
03-02 09:39:02.293  2754  2754 E AndroidRuntime: at android.app.ActivityThread.-667301Nest(Unknown Source:0)
03-02 09:39:02.293  2754  2754 E AndroidRuntime: at android.app.ActivityThread.handleMessage(ActivityThread.java:2281)
03-02 09:39:02.293  2754  2754 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
03-02 09:39:02.293  2754  2754 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:205)
03-02 09:39:02.293  2754  2754 E AndroidRuntime: at android.os.Looper.loop(Looper.java:294)
03-02 09:39:02.293  2754  2754 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8246)
03-02 09:39:02.293  2754  2754 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
03-02 09:39:02.293  2754  2754 E AndroidRuntime: at com.android.internal.os.RuntimeInit.run(RuntimeInit.java:552)
03-02 09:39:02.293  2754  2754 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
03-02 09:39:02.293  2754  2754 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.qualcomm.qcrilhook.QcRilHookCallback
03-02 09:39:02.293  2754  2754 E AndroidRuntime: ... 14 more